### PR TITLE
Add HTTPS exposable JSON RPC and WS to manifest

### PR DESCRIPTION
**Pull request by alexpeterson91**
Add exposable JSON RPC and WS to manifest to fix https://github.com/dappnode/DAppNode/issues/385

### CODE REVIEW

**Comment by 3alpha** [comment]
Does nethermind expose Websocker by default?

**Comment by alexpeterson91** [comment]
> Does nethermind expose Websocker by default?

AFAIK yes. I copied the nethermind mainnet exposable services for the nethermind xDai package and this docker-compose.yml file calls for websockets enabled. image

**Comment by 3alpha** [comment]
Great. I approved changes to get CI running.

**Review by dapplion — CHANGES_REQUESTED** [review]
You should copy all the data you had in the previous PR
```
      fromSubdomain: "nethermind-xdai",
      dnpName: "nethermind-xdai.dappnode.eth",
      serviceName: "nethermind-xdai.dappnode.eth",
      port: 8545,
      name: "Nethermind xDai JSON RPC",
      description: "JSON RPC endpoint for Nethermind Gnosis Chain (xDai)"
```

**Comment by alexpeterson91** [comment]
Can do,
just wasn’t sure how to include that info as it's not enumerated in the manifest docs.

**Comment by alexpeterson91** [comment]
@dapplion please re-review and let me know if this is good to go? i hope to help finish carlos testing nethermind so if it works we can push it to the xdai version too and get a new version published next week since this is not good so far, people cant run nethermind too many issues, and OE still doesnt work, can someone please try and fix that API? or at least put me in touch with someone at Gnosis so i can follow up on various things?  like i need to get them to push a new deposit CLI release etc, will make key generation so much easier, and will make the presentation in Denver that much easier as well.  no docker needed!

**Comment by bh2smith** [comment]
Seems that CI has been queued here for over a day... 

```
Requested labels: ubuntu-16.04
Job defined at: dappnode/DAppNodePackage-nethermind-xdai/.github/workflows/main.yml@refs/pull/21/merge
Waiting for a runner to pick up this job...
```

**Review by 3alpha — APPROVED** [review]

**Review by dapplion — APPROVED** [review]
Looks good!

**Comment by alexpeterson91** [comment]
> Looks good!

doesnt install, the formatting syntax in the manifest must be wrong. theres no docs about the info you asked me to add so i dont know if thats the problem or not.  Also the example manifest exposable only has one service and im trying to do 2, i thought i did the object array properly but im not sure since i can build it but it wont complete installing, CI checks failed not sure how to proceed

**Comment by dapplion** [comment]
> doesnt install, the formatting syntax in the manifest must be wrong

What error do you see in the UI? Could you provide more info about what's preventing the installation?

**Pull request merged**
